name: openlabel
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - libexpat=2.6.4
  - libffi=3.4.6
  - liblzma=5.6.4
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - nodejs=22.13.0
  - openssl=3.5.0
  - pip=25.0.1
  - python=3.12.9
  - setuptools=75.8.2
  - tk=8.6.13
  - tzdata=2025a
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.42.34438
  - wheel=0.45.1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - click==8.1.8
      - colorama==0.4.6
      - cryptography==44.0.2
      - dnspython==2.7.0
      - ecdsa==0.19.1
      - email-validator==2.2.0
      - fastapi==0.115.11
      - fastapi-cli==0.0.7
      - h11==0.14.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - idna==3.10
      - jinja2==3.1.6
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - pyasn1==0.4.8
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-settings==2.8.1
      - pygments==2.19.1
      - python-dotenv==1.0.1
      - python-jose==3.4.0
      - python-multipart==0.0.20
      - pyyaml==6.0.2
      - rich==13.9.4
      - rich-toolkit==0.13.2
      - rsa==4.9
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.46.1
      - typer==0.15.2
      - typing-extensions==4.12.2
      - uvicorn==0.34.0
      - watchfiles==1.0.4
      - websockets==15.0.1
